% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef AnnulusShapeSerializer < yardl.binary.RecordSerializer
  methods
    function self = AnnulusShapeSerializer()
      field_serializers{1} = yardl.binary.Float32Serializer;
      field_serializers{2} = yardl.binary.Float32Serializer;
      field_serializers{3} = yardl.binary.Float32Serializer;
      field_serializers{4} = yardl.binary.FixedVectorSerializer(yardl.binary.Float32Serializer, 2);
      self@yardl.binary.RecordSerializer('petsird.AnnulusShape', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.AnnulusShape
      end
      self.write_(outstream, value.inner_radius, value.outer_radius, value.thickness, value.angular_range);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.AnnulusShape(inner_radius=fields{1}, outer_radius=fields{2}, thickness=fields{3}, angular_range=fields{4});
    end
  end
end
