% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef AtomSerializer < yardl.binary.RecordSerializer
  methods
    function self = AtomSerializer()
      field_serializers{1} = yardl.binary.Uint32Serializer;
      field_serializers{2} = yardl.binary.Uint32Serializer;
      self@yardl.binary.RecordSerializer('petsird.Atom', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.Atom
      end
      self.write_(outstream, value.mass_number, value.atomic_number);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.Atom(mass_number=fields{1}, atomic_number=fields{2});
    end
  end
end
