% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef BoxShapeSerializer < yardl.binary.RecordSerializer
  methods
    function self = BoxShapeSerializer()
      field_serializers{1} = yardl.binary.FixedVectorSerializer(petsird.binary.CoordinateSerializer(), 8);
      self@yardl.binary.RecordSerializer('petsird.BoxShape', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.BoxShape
      end
      self.write_(outstream, value.corners);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.BoxShape(corners=fields{1});
    end
  end
end
