% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef BulkMaterialSerializer < yardl.binary.RecordSerializer
  methods
    function self = BulkMaterialSerializer()
      field_serializers{1} = yardl.binary.Uint32Serializer;
      field_serializers{2} = yardl.binary.StringSerializer;
      field_serializers{3} = yardl.binary.Float32Serializer;
      field_serializers{4} = yardl.binary.VectorSerializer(petsird.binary.AtomSerializer());
      field_serializers{5} = yardl.binary.VectorSerializer(yardl.binary.Float32Serializer);
      self@yardl.binary.RecordSerializer('petsird.BulkMaterial', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.BulkMaterial
      end
      self.write_(outstream, value.id, value.name, value.density, value.atoms, value.mass_fractions);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.BulkMaterial(id=fields{1}, name=fields{2}, density=fields{3}, atoms=fields{4}, mass_fractions=fields{5});
    end
  end
end
