% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef CoincidenceEventSerializer < yardl.binary.RecordSerializer
  methods
    function self = CoincidenceEventSerializer()
      field_serializers{1} = yardl.binary.FixedVectorSerializer(yardl.binary.Uint32Serializer, 2);
      field_serializers{2} = yardl.binary.Uint32Serializer;
      field_serializers{3} = yardl.binary.FixedVectorSerializer(yardl.binary.Uint32Serializer, 2);
      self@yardl.binary.RecordSerializer('petsird.CoincidenceEvent', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.CoincidenceEvent
      end
      self.write_(outstream, value.detector_ids, value.tof_idx, value.energy_indices);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.CoincidenceEvent(detector_ids=fields{1}, tof_idx=fields{2}, energy_indices=fields{3});
    end
  end
end
