% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef DeadTimeTimeBlockSerializer < yardl.binary.RecordSerializer
  methods
    function self = DeadTimeTimeBlockSerializer()
      field_serializers{1} = petsird.binary.TimeIntervalSerializer();
      field_serializers{2} = yardl.binary.NDArraySerializer(yardl.binary.Float32Serializer, 2);
      field_serializers{3} = yardl.binary.NDArraySerializer(yardl.binary.Float32Serializer, 2);
      self@yardl.binary.RecordSerializer('petsird.DeadTimeTimeBlock', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.DeadTimeTimeBlock
      end
      self.write_(outstream, value.time_interval, value.singles_alive_time_fraction, value.module_coincidence_alive_time_fraction);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.DeadTimeTimeBlock(time_interval=fields{1}, singles_alive_time_fraction=fields{2}, module_coincidence_alive_time_fraction=fields{3});
    end
  end
end
