% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef DetectionEfficienciesSerializer < yardl.binary.RecordSerializer
  methods
    function self = DetectionEfficienciesSerializer()
      field_serializers{1} = yardl.binary.OptionalSerializer(yardl.binary.NDArraySerializer(yardl.binary.Float32Serializer, 2));
      field_serializers{2} = yardl.binary.OptionalSerializer(yardl.binary.NDArraySerializer(yardl.binary.Int32Serializer, 2));
      field_serializers{3} = yardl.binary.OptionalSerializer(yardl.binary.VectorSerializer(petsird.binary.ModulePairEfficienciesSerializer()));
      self@yardl.binary.RecordSerializer('petsird.DetectionEfficiencies', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.DetectionEfficiencies
      end
      self.write_(outstream, value.det_el_efficiencies, value.module_pair_sgidlut, value.module_pair_efficiencies_vector);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.DetectionEfficiencies(det_el_efficiencies=fields{1}, module_pair_sgidlut=fields{2}, module_pair_efficiencies_vector=fields{3});
    end
  end
end
