% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef DetectorModuleSerializer < yardl.binary.RecordSerializer
  methods
    function self = DetectorModuleSerializer()
      field_serializers{1} = yardl.binary.VectorSerializer(petsird.binary.ReplicatedObjectSerializer(petsird.binary.SolidVolumeSerializer(petsird.binary.BoxShapeSerializer())));
      field_serializers{2} = yardl.binary.VectorSerializer(yardl.binary.Uint32Serializer);
      field_serializers{3} = yardl.binary.VectorSerializer(petsird.binary.ReplicatedObjectSerializer(petsird.binary.SolidVolumeSerializer(yardl.binary.UnionSerializer('petsird.GeometricShape', {petsird.binary.BoxShapeSerializer(), petsird.binary.AnnulusShapeSerializer()}, {@petsird.GeometricShape.BoxShape, @petsird.GeometricShape.AnnulusShape}))));
      self@yardl.binary.RecordSerializer('petsird.DetectorModule', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.DetectorModule
      end
      self.write_(outstream, value.detecting_elements, value.detecting_element_ids, value.non_detecting_elements);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.DetectorModule(detecting_elements=fields{1}, detecting_element_ids=fields{2}, non_detecting_elements=fields{3});
    end
  end
end
