% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef DirectionMatrixSerializer < yardl.binary.RecordSerializer
  methods
    function self = DirectionMatrixSerializer()
      field_serializers{1} = yardl.binary.FixedNDArraySerializer(yardl.binary.Float32Serializer, [3, 3]);
      self@yardl.binary.RecordSerializer('petsird.DirectionMatrix', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.DirectionMatrix
      end
      self.write_(outstream, value.matrix);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.DirectionMatrix(matrix=fields{1});
    end
  end
end
