% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef DirectionSerializer < yardl.binary.RecordSerializer
  methods
    function self = DirectionSerializer()
      field_serializers{1} = yardl.binary.FixedNDArraySerializer(yardl.binary.Float32Serializer, [3]);
      self@yardl.binary.RecordSerializer('petsird.Direction', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.Direction
      end
      self.write_(outstream, value.c);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.Direction(c=fields{1});
    end
  end
end
