% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef EventTimeBlockSerializer < yardl.binary.RecordSerializer
  methods
    function self = EventTimeBlockSerializer()
      field_serializers{1} = yardl.binary.Uint32Serializer;
      field_serializers{2} = yardl.binary.VectorSerializer(petsird.binary.CoincidenceEventSerializer());
      field_serializers{3} = yardl.binary.OptionalSerializer(yardl.binary.VectorSerializer(petsird.binary.CoincidenceEventSerializer()));
      field_serializers{4} = yardl.binary.OptionalSerializer(yardl.binary.VectorSerializer(petsird.binary.TripleEventSerializer()));
      self@yardl.binary.RecordSerializer('petsird.EventTimeBlock', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.EventTimeBlock
      end
      self.write_(outstream, value.start, value.prompt_events, value.delayed_events, value.triple_events);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.EventTimeBlock(start=fields{1}, prompt_events=fields{2}, delayed_events=fields{3}, triple_events=fields{4});
    end
  end
end
