% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ExamInformationSerializer < yardl.binary.RecordSerializer
  methods
    function self = ExamInformationSerializer()
      field_serializers{1} = petsird.binary.SubjectSerializer();
      field_serializers{2} = petsird.binary.InstitutionSerializer();
      field_serializers{3} = yardl.binary.OptionalSerializer(yardl.binary.StringSerializer);
      field_serializers{4} = yardl.binary.OptionalSerializer(yardl.binary.DatetimeSerializer);
      self@yardl.binary.RecordSerializer('petsird.ExamInformation', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.ExamInformation
      end
      self.write_(outstream, value.subject, value.institution, value.protocol, value.start_of_acquisition);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.ExamInformation(subject=fields{1}, institution=fields{2}, protocol=fields{3}, start_of_acquisition=fields{4});
    end
  end
end
