% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ExternalSignalTypeSerializer < yardl.binary.RecordSerializer
  methods
    function self = ExternalSignalTypeSerializer()
      field_serializers{1} = yardl.binary.EnumSerializer('petsird.ExternalSignalTypeEnum', @petsird.ExternalSignalTypeEnum, yardl.binary.Int32Serializer);
      field_serializers{2} = yardl.binary.StringSerializer;
      field_serializers{3} = yardl.binary.Uint32Serializer;
      self@yardl.binary.RecordSerializer('petsird.ExternalSignalType', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.ExternalSignalType
      end
      self.write_(outstream, value.type, value.description, value.id);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.ExternalSignalType(type=fields{1}, description=fields{2}, id=fields{3});
    end
  end
end
