% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ExternalSignalTimeBlockSerializer < yardl.binary.RecordSerializer
  methods
    function self = ExternalSignalTimeBlockSerializer()
      field_serializers{1} = yardl.binary.Uint32Serializer;
      field_serializers{2} = yardl.binary.Uint32Serializer;
      field_serializers{3} = yardl.binary.VectorSerializer(yardl.binary.Float32Serializer);
      self@yardl.binary.RecordSerializer('petsird.ExternalSignalTimeBlock', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.ExternalSignalTimeBlock
      end
      self.write_(outstream, value.start, value.signal_id, value.signal_values);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.ExternalSignalTimeBlock(start=fields{1}, signal_id=fields{2}, signal_values=fields{3});
    end
  end
end
