% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef GantryMovementTimeBlockSerializer < yardl.binary.RecordSerializer
  methods
    function self = GantryMovementTimeBlockSerializer()
      field_serializers{1} = yardl.binary.Uint32Serializer;
      field_serializers{2} = petsird.binary.RigidTransformationSerializer();
      self@yardl.binary.RecordSerializer('petsird.GantryMovementTimeBlock', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.GantryMovementTimeBlock
      end
      self.write_(outstream, value.start, value.transform);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.GantryMovementTimeBlock(start=fields{1}, transform=fields{2});
    end
  end
end
