% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef HeaderSerializer < yardl.binary.RecordSerializer
  methods
    function self = HeaderSerializer()
      field_serializers{1} = petsird.binary.ScannerInformationSerializer();
      field_serializers{2} = yardl.binary.OptionalSerializer(petsird.binary.ExamInformationSerializer());
      self@yardl.binary.RecordSerializer('petsird.Header', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.Header
      end
      self.write_(outstream, value.scanner, value.exam);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.Header(scanner=fields{1}, exam=fields{2});
    end
  end
end
