% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef InstitutionSerializer < yardl.binary.RecordSerializer
  methods
    function self = InstitutionSerializer()
      field_serializers{1} = yardl.binary.StringSerializer;
      field_serializers{2} = yardl.binary.StringSerializer;
      self@yardl.binary.RecordSerializer('petsird.Institution', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.Institution
      end
      self.write_(outstream, value.name, value.address);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.Institution(name=fields{1}, address=fields{2});
    end
  end
end
