% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ModulePairEfficienciesSerializer < yardl.binary.RecordSerializer
  methods
    function self = ModulePairEfficienciesSerializer()
      field_serializers{1} = yardl.binary.NDArraySerializer(yardl.binary.Float32Serializer, 4);
      field_serializers{2} = yardl.binary.Uint32Serializer;
      self@yardl.binary.RecordSerializer('petsird.ModulePairEfficiencies', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.ModulePairEfficiencies
      end
      self.write_(outstream, value.values, value.sgid);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.ModulePairEfficiencies(values=fields{1}, sgid=fields{2});
    end
  end
end
