% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef PETSIRDReader < yardl.binary.BinaryProtocolReader & petsird.PETSIRDReaderBase
  % Binary reader for the PETSIRD protocol
  % Definition of the stream of data
  properties (Access=protected)
    header_serializer
    time_blocks_serializer
  end

  methods
    function self = PETSIRDReader(filename)
      self@petsird.PETSIRDReaderBase();
      self@yardl.binary.BinaryProtocolReader(filename, petsird.PETSIRDReaderBase.schema);
      self.header_serializer = petsird.binary.HeaderSerializer();
      self.time_blocks_serializer = yardl.binary.StreamSerializer(yardl.binary.UnionSerializer('petsird.TimeBlock', {petsird.binary.EventTimeBlockSerializer(), petsird.binary.ExternalSignalTimeBlockSerializer(), petsird.binary.BedMovementTimeBlockSerializer(), petsird.binary.GantryMovementTimeBlockSerializer()}, {@petsird.TimeBlock.EventTimeBlock, @petsird.TimeBlock.ExternalSignalTimeBlock, @petsird.TimeBlock.BedMovementTimeBlock, @petsird.TimeBlock.GantryMovementTimeBlock}));
    end
  end

  methods (Access=protected)
    function value = read_header_(self)
      value = self.header_serializer.read(self.stream_);
    end

    function more = has_time_blocks_(self)
      more = self.time_blocks_serializer.hasnext(self.stream_);
    end

    function value = read_time_blocks_(self)
      value = self.time_blocks_serializer.read(self.stream_);
    end
  end
end
