% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef PETSIRDWriter < yardl.binary.BinaryProtocolWriter & petsird.PETSIRDWriterBase
  % Binary writer for the PETSIRD protocol
  % Definition of the stream of data
  properties (Access=protected)
    header_serializer
    time_blocks_serializer
  end

  methods
    function self = PETSIRDWriter(filename)
      self@petsird.PETSIRDWriterBase();
      self@yardl.binary.BinaryProtocolWriter(filename, petsird.PETSIRDWriterBase.schema);
      self.header_serializer = petsird.binary.HeaderSerializer();
      self.time_blocks_serializer = yardl.binary.StreamSerializer(yardl.binary.UnionSerializer('petsird.TimeBlock', {petsird.binary.EventTimeBlockSerializer(), petsird.binary.ExternalSignalTimeBlockSerializer(), petsird.binary.BedMovementTimeBlockSerializer(), petsird.binary.GantryMovementTimeBlockSerializer()}, {@petsird.TimeBlock.EventTimeBlock, @petsird.TimeBlock.ExternalSignalTimeBlock, @petsird.TimeBlock.BedMovementTimeBlock, @petsird.TimeBlock.GantryMovementTimeBlock}));
    end
  end

  methods (Access=protected)
    function write_header_(self, value)
      self.header_serializer.write(self.stream_, value);
    end

    function write_time_blocks_(self, value)
      self.time_blocks_serializer.write(self.stream_, value);
    end
  end
end
