% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ReplicatedObjectSerializer < yardl.binary.RecordSerializer
  methods
    function self = ReplicatedObjectSerializer(t_serializer)
      field_serializers{1} = t_serializer;
      field_serializers{2} = yardl.binary.VectorSerializer(petsird.binary.RigidTransformationSerializer());
      field_serializers{3} = yardl.binary.VectorSerializer(yardl.binary.Uint32Serializer);
      self@yardl.binary.RecordSerializer('petsird.ReplicatedObject', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.ReplicatedObject
      end
      self.write_(outstream, value.object, value.transforms, value.ids);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.ReplicatedObject(object=fields{1}, transforms=fields{2}, ids=fields{3});
    end
  end
end
