% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ScannerInformationSerializer < yardl.binary.RecordSerializer
  methods
    function self = ScannerInformationSerializer()
      field_serializers{1} = yardl.binary.StringSerializer;
      field_serializers{2} = petsird.binary.ScannerGeometrySerializer();
      field_serializers{3} = yardl.binary.VectorSerializer(petsird.binary.BulkMaterialSerializer());
      field_serializers{4} = yardl.binary.OptionalSerializer(petsird.binary.RigidTransformationSerializer());
      field_serializers{5} = yardl.binary.NDArraySerializer(yardl.binary.Float32Serializer, 1);
      field_serializers{6} = yardl.binary.Float32Serializer;
      field_serializers{7} = yardl.binary.NDArraySerializer(yardl.binary.Float32Serializer, 1);
      field_serializers{8} = yardl.binary.Float32Serializer;
      field_serializers{9} = yardl.binary.Uint32Serializer;
      field_serializers{10} = yardl.binary.EnumSerializer('petsird.CoincidencePolicy', @petsird.CoincidencePolicy, yardl.binary.Int32Serializer);
      field_serializers{11} = petsird.binary.DetectionEfficienciesSerializer();
      self@yardl.binary.RecordSerializer('petsird.ScannerInformation', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.ScannerInformation
      end
      self.write_(outstream, value.model_name, value.scanner_geometry, value.bulk_materials, value.gantry_alignment, value.tof_bin_edges, value.tof_resolution, value.energy_bin_edges, value.energy_resolution_at_511, value.event_time_block_duration, value.coincidence_policy, value.detection_efficiencies);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.ScannerInformation(model_name=fields{1}, scanner_geometry=fields{2}, bulk_materials=fields{3}, gantry_alignment=fields{4}, tof_bin_edges=fields{5}, tof_resolution=fields{6}, energy_bin_edges=fields{7}, energy_resolution_at_511=fields{8}, event_time_block_duration=fields{9}, coincidence_policy=fields{10}, detection_efficiencies=fields{11});
    end
  end
end
