% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ScannerGeometrySerializer < yardl.binary.RecordSerializer
  methods
    function self = ScannerGeometrySerializer()
      field_serializers{1} = yardl.binary.VectorSerializer(petsird.binary.ReplicatedObjectSerializer(petsird.binary.DetectorModuleSerializer()));
      field_serializers{2} = yardl.binary.VectorSerializer(yardl.binary.Uint32Serializer);
      field_serializers{3} = yardl.binary.OptionalSerializer(yardl.binary.VectorSerializer(petsird.binary.SolidVolumeSerializer(yardl.binary.UnionSerializer('petsird.GeometricShape', {petsird.binary.BoxShapeSerializer(), petsird.binary.AnnulusShapeSerializer()}, {@petsird.GeometricShape.BoxShape, @petsird.GeometricShape.AnnulusShape}))));
      self@yardl.binary.RecordSerializer('petsird.ScannerGeometry', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.ScannerGeometry
      end
      self.write_(outstream, value.replicated_modules, value.ids, value.non_detecting_volumes);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.ScannerGeometry(replicated_modules=fields{1}, ids=fields{2}, non_detecting_volumes=fields{3});
    end
  end
end
