% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef SolidVolumeSerializer < yardl.binary.RecordSerializer
  methods
    function self = SolidVolumeSerializer(shape_serializer)
      field_serializers{1} = shape_serializer;
      field_serializers{2} = yardl.binary.Uint32Serializer;
      self@yardl.binary.RecordSerializer('petsird.SolidVolume', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.SolidVolume
      end
      self.write_(outstream, value.shape, value.material_id);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.SolidVolume(shape=fields{1}, material_id=fields{2});
    end
  end
end
