% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef SubjectSerializer < yardl.binary.RecordSerializer
  methods
    function self = SubjectSerializer()
      field_serializers{1} = yardl.binary.OptionalSerializer(yardl.binary.StringSerializer);
      field_serializers{2} = yardl.binary.StringSerializer;
      self@yardl.binary.RecordSerializer('petsird.Subject', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.Subject
      end
      self.write_(outstream, value.name, value.id);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.Subject(name=fields{1}, id=fields{2});
    end
  end
end
