% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef TimeIntervalSerializer < yardl.binary.RecordSerializer
  methods
    function self = TimeIntervalSerializer()
      field_serializers{1} = yardl.binary.Uint32Serializer;
      field_serializers{2} = yardl.binary.Uint32Serializer;
      self@yardl.binary.RecordSerializer('petsird.TimeInterval', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.TimeInterval
      end
      self.write_(outstream, value.start, value.stop);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.TimeInterval(start=fields{1}, stop=fields{2});
    end
  end
end
