% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef TimeFrameInformationSerializer < yardl.binary.RecordSerializer
  methods
    function self = TimeFrameInformationSerializer()
      field_serializers{1} = yardl.binary.VectorSerializer(petsird.binary.TimeIntervalSerializer());
      self@yardl.binary.RecordSerializer('petsird.TimeFrameInformation', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.TimeFrameInformation
      end
      self.write_(outstream, value.time_frames);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.TimeFrameInformation(time_frames=fields{1});
    end
  end
end
