% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef TripleEventSerializer < yardl.binary.RecordSerializer
  methods
    function self = TripleEventSerializer()
      field_serializers{1} = yardl.binary.FixedVectorSerializer(yardl.binary.Uint32Serializer, 3);
      field_serializers{2} = yardl.binary.FixedVectorSerializer(yardl.binary.Uint32Serializer, 2);
      field_serializers{3} = yardl.binary.FixedVectorSerializer(yardl.binary.Uint32Serializer, 3);
      self@yardl.binary.RecordSerializer('petsird.TripleEvent', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) petsird.TripleEvent
      end
      self.write_(outstream, value.detector_ids, value.tof_indices, value.energy_indices);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = petsird.TripleEvent(detector_ids=fields{1}, tof_indices=fields{2}, energy_indices=fields{3});
    end
  end
end
