% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef BedMovementTimeBlock < handle
  properties
    % start time since ExamInformation.startOfAcquisition in ms
    start
    transform
  end

  methods
    function self = BedMovementTimeBlock(kwargs)
      arguments
        kwargs.start = uint32(0);
        kwargs.transform = petsird.RigidTransformation();
      end
      self.start = kwargs.start;
      self.transform = kwargs.transform;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.BedMovementTimeBlock") && ...
        isequal({self.start}, {other.start}) && ...
        isequal({self.transform}, {other.transform});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.BedMovementTimeBlock();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
