% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef CoincidencePolicy < uint64
  % Type definition for how to encode how the scanner handles multiple coincidences when recording the prompts.
  % Due to various effects (such as high count rate, prompt gammas), it is possible that multiple single
  % events are detected within the coincidence window. This type encodes some different ways
  % that this multiple events are handled, and recorded in the coincidence stream.
  methods (Static)
    % multiples will be rejected
    function v = REJECT_MULTIPLES
      v = petsird.CoincidencePolicy(0);
    end
    % multiples will be stored as a sequence of pairs, e.g. a triple leads to 3 pairs
    function v = STORE_MULTIPLES_AS_PAIRS
      v = petsird.CoincidencePolicy(1);
    end
    % other options, to be listed in the future
    function v = OTHER
      v = petsird.CoincidencePolicy(2);
    end

    function z = zeros(varargin)
      elem = petsird.CoincidencePolicy(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
