% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef CoincidenceEvent < handle
  % All information about a coincidence event specified as identifiers or indices (i.e. discretized). Indices start from 0.
  % TODO: this might take up too much space, so some/all of these could be combined in a single index if necessary.
  properties
    % the pair of detector elements
    detector_ids
    % an index into the tofBinEdges field in the ScannerInformation
    tof_idx
    % a pair of indices into the energyBinEdges field in the ScannerInformation
    energy_indices
  end

  methods
    function self = CoincidenceEvent(kwargs)
      arguments
        kwargs.detector_ids = repelem(uint32(0), 2);
        kwargs.tof_idx = uint32(0);
        kwargs.energy_indices = repelem(uint32(0), 2);
      end
      self.detector_ids = kwargs.detector_ids;
      self.tof_idx = kwargs.tof_idx;
      self.energy_indices = kwargs.energy_indices;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.CoincidenceEvent") && ...
        isequal({self.detector_ids}, {other.detector_ids}) && ...
        isequal({self.tof_idx}, {other.tof_idx}) && ...
        isequal({self.energy_indices}, {other.energy_indices});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.CoincidenceEvent();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
