% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef Coordinate < handle
  % 3D coordinates (in mm)
  properties
    c
  end

  methods
    function self = Coordinate(kwargs)
      arguments
        kwargs.c = repelem(single(0), 3, 1);
      end
      self.c = kwargs.c;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.Coordinate") && ...
        isequal({self.c}, {other.c});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.Coordinate();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
