% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ExamInformation < handle
  % Items describing the exam (incomplete)
  properties
    subject
    institution
    protocol
    start_of_acquisition
  end

  methods
    function self = ExamInformation(kwargs)
      arguments
        kwargs.subject = petsird.Subject();
        kwargs.institution = petsird.Institution();
        kwargs.protocol = yardl.None;
        kwargs.start_of_acquisition = yardl.None;
      end
      self.subject = kwargs.subject;
      self.institution = kwargs.institution;
      self.protocol = kwargs.protocol;
      self.start_of_acquisition = kwargs.start_of_acquisition;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.ExamInformation") && ...
        isequal({self.subject}, {other.subject}) && ...
        isequal({self.institution}, {other.institution}) && ...
        isequal({self.protocol}, {other.protocol}) && ...
        isequal({self.start_of_acquisition}, {other.start_of_acquisition});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.ExamInformation();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
