% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ExternalSignalType < handle
  properties
    type
    description
    id
  end

  methods
    function self = ExternalSignalType(kwargs)
      arguments
        kwargs.type = petsird.ExternalSignalTypeEnum.ECG_TRACE;
        kwargs.description = "";
        kwargs.id = uint32(0);
      end
      self.type = kwargs.type;
      self.description = kwargs.description;
      self.id = kwargs.id;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.ExternalSignalType") && ...
        isequal({self.type}, {other.type}) && ...
        isequal({self.description}, {other.description}) && ...
        isequal({self.id}, {other.id});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.ExternalSignalType();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
