% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ExternalSignalTimeBlock < handle
  properties
    % start time since ExamInformation.startOfAcquisition in ms
    start
    % refer to ExternalSignalType.id
    signal_id
    % Note for triggers, this field is to be ignored
    signal_values
  end

  methods
    function self = ExternalSignalTimeBlock(kwargs)
      arguments
        kwargs.start = uint32(0);
        kwargs.signal_id = uint32(0);
        kwargs.signal_values = single.empty();
      end
      self.start = kwargs.start;
      self.signal_id = kwargs.signal_id;
      self.signal_values = kwargs.signal_values;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.ExternalSignalTimeBlock") && ...
        isequal({self.start}, {other.start}) && ...
        isequal({self.signal_id}, {other.signal_id}) && ...
        isequal({self.signal_values}, {other.signal_values});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.ExternalSignalTimeBlock();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
