% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ExternalSignalTypeEnum < uint64
  methods (Static)
    function v = ECG_TRACE
      v = petsird.ExternalSignalTypeEnum(0);
    end
    function v = ECG_TRIGGER
      v = petsird.ExternalSignalTypeEnum(1);
    end
    function v = RESP_TRACE
      v = petsird.ExternalSignalTypeEnum(2);
    end
    function v = RESP_TRIGGER
      v = petsird.ExternalSignalTypeEnum(3);
    end
    function v = OTHER_MOTION_SIGNAL
      v = petsird.ExternalSignalTypeEnum(4);
    end
    function v = OTHER_MOTION_TRIGGER
      v = petsird.ExternalSignalTypeEnum(5);
    end
    function v = EXTERNAL_SYNC
      v = petsird.ExternalSignalTypeEnum(6);
    end
    % other options, to be listed in the future
    function v = OTHER
      v = petsird.ExternalSignalTypeEnum(7);
    end

    function z = zeros(varargin)
      elem = petsird.ExternalSignalTypeEnum(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
