% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef GeometricShape < yardl.Union
  methods (Static)
    function res = BoxShape(value)
      res = petsird.GeometricShape(1, value);
    end

    function res = AnnulusShape(value)
      res = petsird.GeometricShape(2, value);
    end

    function z = zeros(varargin)
      elem = petsird.GeometricShape(0, yardl.None);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end

  methods
    function res = isBoxShape(self)
      res = self.index == 1;
    end

    function res = isAnnulusShape(self)
      res = self.index == 2;
    end

    function eq = eq(self, other)
      eq = isa(other, "petsird.GeometricShape") && all([self.index_] == [other.index_], 'all') && all([self.value] == [other.value], 'all');
    end

    function ne = ne(self, other)
      ne = ~self.eq(other);
    end

    function t = tag(self)
      tags_ = ["BoxShape", "AnnulusShape"];
      t = tags_(self.index_);
    end
  end
end
