% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef Header < handle
  properties
    scanner
    exam
  end

  methods
    function self = Header(kwargs)
      arguments
        kwargs.scanner = petsird.ScannerInformation();
        kwargs.exam = yardl.None;
      end
      self.scanner = kwargs.scanner;
      self.exam = kwargs.exam;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.Header") && ...
        isequal({self.scanner}, {other.scanner}) && ...
        isequal({self.exam}, {other.exam});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.Header();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
