% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef Institution < handle
  properties
    name
    address
  end

  methods
    function self = Institution(kwargs)
      arguments
        kwargs.name = "";
        kwargs.address = "";
      end
      self.name = kwargs.name;
      self.address = kwargs.address;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.Institution") && ...
        isequal({self.name}, {other.name}) && ...
        isequal({self.address}, {other.address});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.Institution();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
