% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ModulePairEfficiencies < handle
  % Efficiency for two detecting elements (det_els) in a pair of modules.
  % This is one component (often called "geometric") of the detection efficiency model.
  % If size along energyBinIdx is 1, the effiencies are assumed to be the same for every energy bin.
  properties
    % Detection efficiency for a pair of detecting elements
    % detElIdx1 and detElIdx2 run from 0 to the number of det_els in each module
    values
    % Symmetry Group Identifier (SGID)
    % This should be a number between 0 and numberOfSGIDs-1
    sgid
  end

  methods
    function self = ModulePairEfficiencies(kwargs)
      arguments
        kwargs.values = single.empty();
        kwargs.sgid = uint32(0);
      end
      self.values = kwargs.values;
      self.sgid = kwargs.sgid;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.ModulePairEfficiencies") && ...
        isequal({self.values}, {other.values}) && ...
        isequal({self.sgid}, {other.sgid});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.ModulePairEfficiencies();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
