% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ReplicatedGenericSolidVolume < petsird.ReplicatedObject
  % A list of identical SolidVolumes<BGeometricShape> at different locations
end
