% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef RigidTransformation < handle
  % Rigid transformation, encoded via homogenous transformation
  % transformed_coord = matrix * [c, 1] (where [c,1] is a column vector)
  % with `c` of type `Coordinate`
  properties
    matrix
  end

  methods
    function self = RigidTransformation(kwargs)
      arguments
        kwargs.matrix = repelem(single(0), 4, 3);
      end
      self.matrix = kwargs.matrix;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.RigidTransformation") && ...
        isequal({self.matrix}, {other.matrix});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.RigidTransformation();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
