% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef Subject < handle
  properties
    name
    id
  end

  methods
    function self = Subject(kwargs)
      arguments
        kwargs.name = yardl.None;
        kwargs.id = "";
      end
      self.name = kwargs.name;
      self.id = kwargs.id;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.Subject") && ...
        isequal({self.name}, {other.name}) && ...
        isequal({self.id}, {other.id});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.Subject();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
