% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef TimeBlock < yardl.Union
  methods (Static)
    function res = EventTimeBlock(value)
      res = petsird.TimeBlock(1, value);
    end

    function res = ExternalSignalTimeBlock(value)
      res = petsird.TimeBlock(2, value);
    end

    function res = BedMovementTimeBlock(value)
      res = petsird.TimeBlock(3, value);
    end

    function res = GantryMovementTimeBlock(value)
      res = petsird.TimeBlock(4, value);
    end

    function z = zeros(varargin)
      elem = petsird.TimeBlock(0, yardl.None);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end

  methods
    function res = isEventTimeBlock(self)
      res = self.index == 1;
    end

    function res = isExternalSignalTimeBlock(self)
      res = self.index == 2;
    end

    function res = isBedMovementTimeBlock(self)
      res = self.index == 3;
    end

    function res = isGantryMovementTimeBlock(self)
      res = self.index == 4;
    end

    function eq = eq(self, other)
      eq = isa(other, "petsird.TimeBlock") && all([self.index_] == [other.index_], 'all') && all([self.value] == [other.value], 'all');
    end

    function ne = ne(self, other)
      ne = ~self.eq(other);
    end

    function t = tag(self)
      tags_ = ["EventTimeBlock", "ExternalSignalTimeBlock", "BedMovementTimeBlock", "GantryMovementTimeBlock"];
      t = tags_(self.index_);
    end
  end
end
