% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef TimeInterval < handle
  % Time interval in milliseconds since start of acquisition
  properties
    start
    stop
  end

  methods
    function self = TimeInterval(kwargs)
      arguments
        kwargs.start = uint32(0);
        kwargs.stop = uint32(0);
      end
      self.start = kwargs.start;
      self.stop = kwargs.stop;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "petsird.TimeInterval") && ...
        isequal({self.start}, {other.start}) && ...
        isequal({self.stop}, {other.stop});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = petsird.TimeInterval();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
